@startuml
!include style.puml
skinparam arrowThickness 1.1
skinparam arrowColor MODEL_COLOR
skinparam classBackgroundColor MODEL_COLOR

AddressBook *-right-> "1" UniquePersonList
AddressBook *-right-> "1" UniqueMeetingList

UniquePersonList -right-> Person
UniqueMeetingList -right-> Meeting

Meeting --> "1..*" Person

Person *--> Name
Person *--> Phone
Person *--> Email
Person *--> Address
Person *--> "*" Tag
Person *--> "*" Position
Person *-right-> "*" Major
Person *-right-> "*" Group
Person *--> "0..1" TimeSlot
Person *--> FollowUp
@enduml
